---
# roles/neo4j_conda.yml - Neo4j installation using conda environment
- name: Create Neo4j installation directory
  file:
    path: "{{ neo4j_install_dir }}"
    state: directory
  become: no

- name: Check if Neo4j is already installed
  stat:
    path: "{{ neo4j_install_dir }}/bin/neo4j"
  register: neo4j_binary_check

- name: Download Neo4j tarball if not installed
  get_url:
    url: "{{ neo4j_download_url }}"
    dest: "/tmp/{{ neo4j_tarball }}"
    mode: '0644'
  when: not neo4j_binary_check.stat.exists

- name: Extract Neo4j tarball to installation directory
  unarchive:
    src: "/tmp/{{ neo4j_tarball }}"
    dest: "{{ neo4j_install_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
  when: not neo4j_binary_check.stat.exists

- name: Configure Neo4j to listen on 0.0.0.0
  lineinfile:
    path: "{{ neo4j_install_dir }}/conf/neo4j.conf"
    regexp: '^#?dbms\.default_listen_address='
    line: 'dbms.default_listen_address=0.0.0.0'
    state: present

- name: Set JAVA_HOME for Neo4j using conda environment
  lineinfile:
    path: "{{ neo4j_install_dir }}/conf/neo4j-wrapper.conf"
    regexp: '^#?wrapper\.java\.command='
    line: "wrapper.java.command={{ finance_env_path }}/bin/java"
    state: present
    create: yes

- name: Create Neo4j systemd service script (cross-platform)
  template:
    src: neo4j_service.j2
    dest: "{{ neo4j_install_dir }}/bin/neo4j-service"
    mode: '0755'

- name: Start Neo4j service using conda Java
  shell: |
    export JAVA_HOME="{{ finance_env_path }}"
    export PATH="{{ finance_env_path }}/bin:$PATH"
    {{ neo4j_install_dir }}/bin/neo4j start
  register: neo4j_start
  failed_when: (neo4j_start.rc != 0) and ("Neo4j is already running" not in neo4j_start.stderr)

- name: Wait for Neo4j to start
  wait_for:
    port: 7474
    host: localhost
    delay: 5
    timeout: 60

- name: Check Neo4j service status
  shell: |
    export JAVA_HOME="{{ finance_env_path }}"
    export PATH="{{ finance_env_path }}/bin:$PATH"
    {{ neo4j_install_dir }}/bin/neo4j status
  register: neo4j_status
  changed_when: false

- name: Display Neo4j service status
  debug:
    msg: |
      🟢 Neo4j Status: {{ neo4j_status.stdout }}
      📊 Web Interface: http://localhost:7474
      🔌 Bolt Connection: bolt://localhost:7687
      ☕ Java Path: {{ finance_env_path }}/bin/java