# SEC Edgar Data Source Configuration
description: "SEC Edgar API for regulatory filings and documents"
enabled: true

data_types:
  - "10K_filings"    # Annual reports
  - "10Q_filings"    # Quarterly reports  
  - "8K_filings"     # Current reports
  - "proxy_filings"  # Proxy statements

api_config:
  base_url: "https://data.sec.gov"
  user_agent: "ZitianSG (wangzitian0@gmail.com)"
  timeout_seconds: 60
  
  # Filing collection settings
  filing_types:
    "10K":
      description: "Annual report (Form 10-K)"
      max_filings: 5
      priority: 1
      
    "10Q":
      description: "Quarterly report (Form 10-Q)"
      max_filings: 8  # 2 years of quarterly reports
      priority: 2
      
    "8K":
      description: "Current report (Form 8-K)"
      max_filings: 20  # Recent significant events
      priority: 3

  # Data collection window
  collection:
    start_date: "2022-01-01"
    end_date: null  # Use current date

rate_limits:
  requests_per_second: 0.5  # SEC rate limit: 10 requests per second
  requests_per_minute: 30
  retry_after_seconds: 2
  max_retries: 3

processing:
  extract_sections:
    - "item_1"     # Business
    - "item_1a"    # Risk Factors
    - "item_2"     # Properties  
    - "item_3"     # Legal Proceedings
    - "item_7"     # Management's Discussion and Analysis
    - "item_8"     # Financial Statements

output_format:
  file_extension: ".txt"
  compression: false
  timestamp_format: "%Y%m%d_%H%M%S"
  naming_pattern: "{ticker}_sec_{filing_type}_{timestamp}_{accession}.txt"