name: 🏛️ Architecture Decision Request
description: Propose a major architectural change or decision
title: "[ADR] "
labels: ["architecture", "decision", "discussion"]
assignees: []

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What needs to be decided and why?
      placeholder: |
        Current situation and problems:
        - Issue 1
        - Issue 2
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: What do you recommend?
      placeholder: |
        Recommended approach:
        - Solution overview
        - Key benefits
        - Implementation approach
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other options were evaluated?
      placeholder: |
        Alternative approaches and why they weren't chosen:
        - Option A: reason
        - Option B: reason
    validations:
      required: false