name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report Template
        
        Thanks for taking the time to report a bug! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (system unusable, data loss)
        - High (major feature broken)
        - Medium (feature partially broken)
        - Low (minor issue, workaround available)
    validations:
      required: true

  - type: input
    id: component
    attributes:
      label: Affected Component
      description: Which component/module is affected?
      placeholder: e.g., spider, ETL, graph_rag, DCF engine
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened that shouldn't have happened?
      placeholder: A clear and concise description of the bug
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should have happened instead?
      placeholder: A clear and concise description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: A clear and concise description of what actually happened
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Run command '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Details about your environment
      placeholder: |
        - OS: [e.g., macOS 14.0, Ubuntu 22.04, Windows 11]
        - Python version: [e.g., 3.12.1]
        - Pixi version: [output of `pixi --version`]
        - Neo4j version: [if applicable]
        - Branch/commit: [git branch and commit hash]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Any error messages, stack traces, or relevant log output
      placeholder: |
        Please paste any relevant log output here.
        
        ```
        Error logs go here
        ```
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: |
        - Screenshots (if applicable)
        - Links to related issues
        - Potential workarounds you've found
        - When this started happening
    validations:
      required: false

  - type: checkboxes
    id: checked-existing
    attributes:
      label: Checked Existing Issues
      description: Have you checked that this bug hasn't already been reported?
      options:
        - label: I have searched existing issues and this bug has not been reported before
          required: true