name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: What's broken? Include steps to reproduce.
      placeholder: |
        What happened:
        
        Steps to reproduce:
        1. 
        2. 
        3. 
        
        Expected: 
        Actual: 
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, component affected, any relevant logs
      placeholder: |
        - OS: 
        - Component: 
        - Branch/commit: 
        - Logs (if any):
    validations:
      required: false