name: 🚀 Feature Implementation
description: Detailed implementation task for a specific feature
title: "[FEATURE] "
labels: ["enhancement", "implementation"]
assignees: []

body:
  - type: textarea
    id: objective
    attributes:
      label: Implementation Objective
      description: What needs to be built?
      placeholder: Clear description of what functionality to implement
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How do we know it's done?
      placeholder: |
        - [ ] Specific outcome 1
        - [ ] Specific outcome 2
        - [ ] Tests pass
    validations:
      required: true

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Implementation details, dependencies, constraints
      placeholder: |
        - Component: 
        - Dependencies: 
        - Technical details: 
    validations:
      required: false