# CI Environment Neo4j Configuration
# Issue #266: Comprehensive Neo4j Testing Infrastructure

neo4j:
  host: "localhost"
  port: 7687
  database: "neo4j"
  
  auth:
    user: "neo4j"
    password: "ci_test_password"
  
  connection:
    timeout: 15
    max_retry_attempts: 2
    pool_max_size: 10
    
  test_settings:
    table_name: "TestNode"
    cleanup_on_exit: true  # Clean up in CI
    performance_baseline_ms: 200  # More lenient for CI
    
  monitoring:
    health_check_interval: 30
    enable_metrics: true
    enable_crud_tests: true