# Development Environment Neo4j Configuration
# Issue #266: Comprehensive Neo4j Testing Infrastructure

neo4j:
  host: "localhost"
  port: 7687
  database: "neo4j"
  
  auth:
    user: "neo4j"
    password: "finance123"
  
  connection:
    timeout: 30
    max_retry_attempts: 3
    pool_max_size: 50
    
  test_settings:
    table_name: "TestNode"
    cleanup_on_exit: false
    performance_baseline_ms: 100
    
  monitoring:
    health_check_interval: 60
    enable_metrics: false
    enable_crud_tests: true