# Production Environment Neo4j Configuration
# Issue #266: Comprehensive Neo4j Testing Infrastructure

neo4j:
  host: "${NEO4J_HOST:-neo4j-prod.internal}"
  port: ${NEO4J_PORT:-7687}
  database: "${NEO4J_DATABASE:-finance_prod}"
  
  auth:
    user: "${NEO4J_USER:-neo4j}"
    password: "${NEO4J_PASSWORD}"
  
  connection:
    timeout: 60
    max_retry_attempts: 5
    pool_max_size: 100
    
  test_settings:
    table_name: "TestNode"
    cleanup_on_exit: false
    performance_baseline_ms: 50  # Stricter for production
    
  monitoring:
    health_check_interval: 60
    enable_metrics: true
    enable_crud_tests: false  # Read-only tests for production safety