# Neo4j Environment-Specific Configuration Overrides
# Issue #266: Improved configuration inheritance system
# 
# This file contains all environment-specific configuration overrides
# Only define parts that differ from base configuration

environments:
  development:
    neo4j:
      host: "localhost"
      auth:
        user: "neo4j"
        password: "finance123"
      # Other settings inherited from database_base.yml
        
  ci:
    neo4j:
      host: "localhost"
      auth:
        user: "neo4j"
        password: "ci_test_password"
      # CI environment specific overrides
      connection:
        timeout: 15           # Shorter timeout for fast failure
        pool_max_size: 10     # Smaller connection pool
      test_settings:
        cleanup_on_exit: true # Auto cleanup test data in CI
        performance_baseline_ms: 200  # More lenient performance requirements in CI
        
  production:
    neo4j:
      # Production environment uses environment variables
      host: "${NEO4J_HOST:-neo4j-prod.internal}"
      port: "${NEO4J_PORT:-7687}"
      database: "${NEO4J_DATABASE:-finance_prod}"
      auth:
        user: "${NEO4J_USER:-neo4j}"
        password: "${NEO4J_PASSWORD}"
      # Production environment specific overrides
      connection:
        timeout: 60           # Longer timeout for stability
        pool_max_size: 100    # Larger connection pool
      test_settings:
        performance_baseline_ms: 50  # Stricter performance requirements in production
      monitoring:
        enable_crud_tests: false     # Production safety - read-only tests