# Neo4j Base Configuration - Shared across all environments
# Issue #266: Improved configuration inheritance system

neo4j:
  # Default connection settings - can be overridden by environment-specific configs
  port: 7687
  database: "neo4j"
  
  # Connection pool settings
  connection:
    timeout: 30
    max_retry_attempts: 3
    pool_max_size: 50
    
  # Test settings
  test_settings:
    table_name: "TestNode"
    cleanup_on_exit: false
    performance_baseline_ms: 100
    
  # Monitoring settings  
  monitoring:
    health_check_interval: 60
    enable_metrics: true
    enable_crud_tests: true