# SSOT Directory Structure Configuration
# This file defines the complete directory structure for the my_finance project
# implementing the Five-Layer Data Architecture from Issue #122

storage:
  backend: "local_filesystem"  # Options: local_filesystem, aws_s3, gcp_gcs, azure_blob
  root_path: "build_data"
  versioning: true
  compression: false

# Five-Layer Data Architecture (Issue #122)
# Implements the official architecture as specified in GitHub Issue #122
layers:
  stage_00_raw:
    description: "Raw Data Layer - Immutable source data"
    purpose: "Original, unmodified data from external sources (stage_00_raw)"
    retention: "permanent"
    subdirs:
      - "sec-edgar"     # SEC Edgar filings by CIK
      - "yfinance"      # Yahoo Finance data by ticker
      - "manual"        # Manual data inputs
      - "reference"     # Reference data (CIK mappings, etc.)
    partitioning:
      - "by_date"       # YYYYMMDD format
      - "by_source"     # sec-edgar, yfinance, etc.
      - "by_ticker"     # Company ticker symbol
    
  stage_01_daily_delta:
    description: "Daily Delta Layer - Incremental daily changes"
    purpose: "Track daily changes and updates to avoid full reprocessing (stage_01_daily_delta)"
    retention: "90_days"
    subdirs:
      - "additions"     # New records added
      - "modifications" # Updated records  
      - "deletions"     # Deprecated/removed records
      - "metadata"      # Change tracking metadata
    partitioning:
      - "by_date"       # YYYYMMDD format
      - "by_change_type" # additions, modifications, deletions
    storage_optimization:
      enabled: true
      method: "diff_based"  # Store only differences
      
  stage_02_daily_index:
    description: "Daily Index Layer - New embeddings, entities, relationships"
    purpose: "Daily incremental index processing (stage_02_daily_index)"
    retention: "30_days"  # Can be regenerated from raw data
    subdirs:
      - "vectors"       # Sentence transformer embeddings
      - "entities"      # Extracted entities (companies, people, concepts)
      - "relationships" # Entity relationships
      - "embeddings"    # Document/text embeddings
      - "indices"       # Search indices (FAISS, etc.)
    partitioning:
      - "by_date"       # Processing date
      - "by_model"      # Embedding model used
    storage_optimization:
      enabled: true
      method: "vector_compression"
      
  stage_03_graph_rag:
    description: "Graph RAG Layer - Unified knowledge base (single source of truth)"
    purpose: "Query-ready unified knowledge graph and vector store (stage_03_graph_rag)"
    retention: "permanent"
    subdirs:
      - "graph_db"     # Neo4j graph database
      - "vector_store" # Consolidated vector store
      - "cache"        # Query result cache
      - "snapshots"    # Point-in-time snapshots
    partitioning:
      - "by_version"    # Knowledge base version
      - "by_domain"     # Financial domain segmentation
    storage_optimization:
      enabled: true
      method: "graph_compression"
      
  stage_04_query_results:
    description: "Query Results Layer - Query and analysis results"
    purpose: "Final outputs, reports, and analysis results (stage_04_query_results)"
    retention: "permanent"  # Business value
    subdirs:
      - "dcf_reports"   # DCF valuation reports
      - "analytics"     # Analysis results
      - "exports"       # Exported data sets
      - "dashboards"    # Dashboard data
      - "api_responses" # API response cache
    partitioning:
      - "by_date"       # Report generation date
      - "by_type"       # dcf, analytics, etc.
      - "by_ticker"     # Company focus
    storage_optimization:
      enabled: false    # Keep full fidelity for business use

# Common directories (outside data layers)
common:
  config: "common/config"
  logs: "build_data/logs"  # Logs are build artifacts - use build_data structure
  temp: "temp" 
  cache: "cache"
  scripts: "scripts"
  templates: "templates"

# Legacy path mapping for backward compatibility (Issue #122)
legacy_mapping:
  # Old stage naming → New Issue #122 architecture
  stage_00_original: "stage_00_raw"
  stage_01_extract: "stage_01_daily_delta"
  stage_02_transform: "stage_02_daily_index" 
  stage_03_load: "stage_03_graph_rag"
  stage_99_build: "stage_04_query_results"
  
  # Old layer naming → New Issue #122 architecture  
  layer_01_raw: "stage_00_raw"
  layer_02_delta: "stage_01_daily_delta"
  layer_03_index: "stage_02_daily_index"
  layer_04_rag: "stage_03_graph_rag"
  layer_05_results: "stage_04_query_results"
  
  # Directory migration
  data/config: "common/config"  # Migrated to main repo
  data: "build_data"  # Data directory renamed to build_data subtree

# Data layer enum mapping (for DataLayer enum in directory_manager.py)
data_layer_mapping:
  RAW_DATA: "stage_00_raw"
  DAILY_DELTA: "stage_01_daily_delta" 
  DAILY_INDEX: "stage_02_daily_index"
  GRAPH_RAG: "stage_03_graph_rag"
  QUERY_RESULTS: "stage_04_query_results"

# Storage backend configurations
backends:
  local_filesystem:
    compression: false
    encryption: false
    
  aws_s3:
    bucket_prefix: "my-finance"
    region: "us-west-2"
    compression: true
    encryption: true
    lifecycle_policies: true
    
  gcp_gcs:
    bucket_prefix: "my-finance"
    region: "us-west1"
    compression: true
    encryption: true
    
  azure_blob:
    container_prefix: "my-finance"
    region: "westus2"
    compression: true
    encryption: true

# Performance optimizations per layer (Issue #122)
performance:
  stage_00_raw:
    indexing: "minimal"  # Raw data doesn't need heavy indexing
    caching: false
    target_response_time: "1000ms"  # Raw data access
    
  stage_01_daily_delta:
    indexing: "temporal"  # Index by date for fast delta queries
    caching: false
    target_response_time: "500ms"  # Delta processing
    
  stage_02_daily_index:
    indexing: "full"     # Heavy indexing for vector/entity search
    caching: true
    cache_ttl: "24h"
    target_response_time: "200ms"  # Index lookup
    
  stage_03_graph_rag:
    indexing: "graph"    # Graph-specific indexing
    caching: true
    cache_ttl: "1h"      # Frequent queries, shorter TTL
    target_response_time: "100ms"  # Target <100ms from Issue #122
    
  stage_04_query_results:
    indexing: "business" # Business-logic indexing
    caching: true
    cache_ttl: "7d"      # Reports don't change often
    target_response_time: "50ms"   # Cached results