# Magnificent 7 - 7 companies for standard PR testing
dataset_name: magnificent_7
cli_alias: m7
description: "Magnificent 7 companies for standard PR testing and performance validation"
companies:
  - ticker: AAPL
    name: "Apple Inc."
    cik: "0000320193"
  - ticker: MSFT
    name: "Microsoft Corporation"
    cik: "0000789019"
  - ticker: GOOGL
    name: "Alphabet Inc."
    cik: "0001652044"
  - ticker: AMZN
    name: "Amazon.com Inc."
    cik: "0001018724"
  - ticker: NVDA
    name: "NVIDIA Corporation"
    cik: "0001045810"
  - ticker: TSLA
    name: "Tesla Inc."
    cik: "0001318605"
  - ticker: META
    name: "Meta Platforms Inc."
    cik: "0001326801"