# Fast Testing - 2 companies for CI validation
dataset_name: fast_2
cli_alias: f2
description: "Fast 2 companies for development and CI testing"
companies:
  - ticker: MSFT
    name: "Microsoft Corporation"
    cik: "0000789019"
  - ticker: NVDA
    name: "NVIDIA Corporation"
    cik: "0001045810"