# Fast Test Ticker List Configuration
# 2-company subset from M7 for rapid development testing
# References M7 companies but only includes fastest-processing tickers

dataset_name: "fast_2"
cli_alias: "fast"
description: "Fast 2-company test dataset for development"
tier: 1  # Test tier
tracked_in_git: false
max_size_mb: 20

# Reference M7 configuration and select 2 fastest companies
reference_config: "list_magnificent_7.yml"
selected_companies: ["MSFT", "NVDA"]  # Selected for speed and reliability
ticker_count: 2

# Data source attribution
data_source_info:
  primary_source: "Reference to Magnificent 7 dataset"
  last_verified: "2025-08-19"
  update_method: "Automatic selection from M7 configuration"
  selection_criteria: "2 fastest-processing companies from M7 for development testing"
  notes: "Subset of M7 companies optimized for rapid development iteration"

# Fast data collection for PR validation
data_sources:
  yfinance:
    enabled: true
    stage_config: "stage_00_original_yfinance.yml"
    periods: ["daily_3mo"]  # Override: Single period for speed
    
  sec_edgar:
    enabled: true   # Enabled for SEC testing
    stage_config: "stage_00_original_sec_edgar.yml"

# Expected file counts
expected_files:
  yfinance: 2  # 2 tickers × 1 period
  sec_edgar: 66  # 2 tickers × 33 filings max (5+8+20 from stage_00_original_sec_edgar.yml)
  
# Fast validation settings
validation:
  timeout_seconds: 120  # 2 minutes max
  required_success_rate: 1.0
  min_files_threshold: 2

last_updated: "2025-08-10T03:45:00.000000"