---
# roles/repo_data.yml
# Verify data directory exists (now integrated in main repository)

- name: Set data directory path
  set_fact:
    data_dir_path: "{{ repo_dir }}/data"

- name: Remove legacy .gitmodules if present
  file:
    path: "{{ repo_dir }}/.gitmodules"
    state: absent

- name: Remove legacy .git/modules/data if present
  file:
    path: "{{ repo_dir }}/.git/modules/data"
    state: absent

- name: Check if data directory exists
  stat:
    path: "{{ data_dir_path }}"
  register: data_dir_stat

- name: Fail if data directory is missing
  fail:
    msg: "Data directory not found at {{ data_dir_path }}. Data should be part of the main repository."
  when: not (data_dir_stat.stat.exists | default(false))

- name: Verify data directory is a regular directory (not a symlink)
  fail:
    msg: "Data directory at {{ data_dir_path }} is still a symlink. Please merge data into main repository."
  when: data_dir_stat.stat.islnk | default(false)

- name: Summary for data directory verification
  debug:
    msg: |
      ✅ Data directory ready.
      - Data path: {{ data_dir_path }}
      - Type: Regular directory (integrated in main repository)
