# M7 - Small Test Dataset (Git Managed)
# Purpose: Stable test dataset with complete records tracked in git
# This is the only dataset that should be committed to git for testing
job: m7
source: yfinance
description: "M7 - Git-managed test dataset (7 companies, complete records tracked in git)"

# Magnificent 7 stock tickers (updated to include META instead of FB)
tickers:
  - AAPL    # Apple Inc.
  - MSFT    # Microsoft Corporation
  - GOOGL   # Alphabet Inc. Class A
  - AMZN    # Amazon.com Inc.
  - NVDA    # NVIDIA Corporation
  - META    # Meta Platforms Inc.
  - TSLA    # Tesla Inc.

# Data collection periods and intervals
data_periods:
  - oid: 1y_1d
    period: 1y
    interval: 1d
  - oid: 5y_1wk
    period: 5y
    interval: 1wk
  - oid: 3mo_1d
    period: 3mo
    interval: 1d
