job: yfinance_m7
source: yfinance
description: "Fetch data for the 7 major US stocks (using yfinance library)"
tickers:
  - AAPL
  - MSFT
  - AMZN
  - GOOGL
  - FB
  - TSLA
  - NFLX
data_periods:
  - oid: "D1"    # Represents 1 year of daily data
    period: "1y"
    interval: "1d"
  - oid: "W7"    # Represents 7 years of weekly data
    period: "7y"
    interval: "1wk"
  - oid: "M30"   # Represents 30 years of monthly data
    period: "30y"
    interval: "1mo"
