dataset_name: nasdaq100
cli_alias: n100
description: NASDAQ-100 index companies - validation dataset
tier: 3
tracked_in_git: false
max_size_mb: 5000
companies:
  AAPL:
    name: Apple Inc. Common Stock
    sector: ''
    market_cap: 3,403,643,446,500
  AMAT:
    name: Applied Materials, Inc. Common Stock
    sector: ''
    market_cap: 148,357,845,377
  AMGN:
    name: Amgen Inc. Common Stock
    sector: ''
    market_cap: 155,172,036,314
  CMCSA:
    name: Comcast Corporation Class A Common Stock
    sector: ''
    market_cap: 116,932,179,918
  INTC:
    name: Intel Corporation Common Stock
    sector: ''
    market_cap: 87,321,150,000
  KLAC:
    name: KLA Corporation Common Stock
    sector: ''
    market_cap: 120,974,460,164
  PCAR:
    name: PACCAR Inc. Common Stock
    sector: ''
    market_cap: 51,113,564,177
  CTAS:
    name: Cintas Corporation Common Stock
    sector: ''
    market_cap: 91,181,815,316
  PAYX:
    name: Paychex, Inc. Common Stock
    sector: ''
    market_cap: 50,862,832,994
  LRCX:
    name: Lam Research Corporation Common Stock
    sector: ''
    market_cap: 130,150,256,500
  ADSK:
    name: Autodesk, Inc. Common Stock
    sector: ''
    market_cap: 62,205,520,000
  ROST:
    name: Ross Stores, Inc. Common Stock
    sector: ''
    market_cap: 47,497,181,060
  MNST:
    name: Monster Beverage Corporation
    sector: ''
    market_cap: 63,088,674,026
  MSFT:
    name: Microsoft Corporation Common Stock
    sector: ''
    market_cap: 3,880,410,176,493
  ADBE:
    name: Adobe Inc. Common Stock
    sector: ''
    market_cap: 144,673,410,000
  FAST:
    name: Fastenal Company Common Stock
    sector: ''
    market_cap: 55,075,081,250
  EA:
    name: Electronic Arts Inc. Common Stock
    sector: ''
    market_cap: 41,944,752,275
  CSCO:
    name: Cisco Systems, Inc. Common Stock (DE)
    sector: ''
    market_cap: 284,288,269,342
  REGN:
    name: Regeneron Pharmaceuticals, Inc. Common Stock
    sector: ''
    market_cap: 59,670,929,846
  IDXX:
    name: IDEXX Laboratories, Inc. Common Stock
    sector: ''
    market_cap: 52,647,888,934
  VRTX:
    name: Vertex Pharmaceuticals Incorporated Common Stock
    sector: ''
    market_cap: 93,977,429,218
  BIIB:
    name: Biogen Inc. Common Stock
    sector: ''
    market_cap: 19,158,129,521
  ODFL:
    name: Old Dominion Freight Line, Inc. Common Stock
    sector: ''
    market_cap: 30,360,889,071
  QCOM:
    name: QUALCOMM Incorporated Common Stock
    sector: ''
    market_cap: 159,217,240,000
  GILD:
    name: Gilead Sciences, Inc. Common Stock
    sector: ''
    market_cap: 148,537,576,339
  SNPS:
    name: Synopsys, Inc. Common Stock
    sector: ''
    market_cap: 96,109,788,216
  SBUX:
    name: Starbucks Corporation Common Stock
    sector: ''
    market_cap: 104,712,804,000
  INTU:
    name: Intuit Inc. Common Stock
    sector: ''
    market_cap: 208,931,303,000
  MCHP:
    name: Microchip Technology Incorporated Common Stock
    sector: ''
    market_cap: 33,372,643,724
  ORLY:
    name: O'Reilly Automotive, Inc. Common Stock
    sector: ''
    market_cap: 88,330,364,145
  COST:
    name: Costco Wholesale Corporation Common Stock
    sector: ''
    market_cap: 435,042,151,824
  CPRT:
    name: Copart, Inc. (DE) Common Stock
    sector: ''
    market_cap: 44,657,949,044
  ASML:
    name: ASML Holding N.V. New York Registry Shares
    sector: ''
    market_cap: 284,076,696,630
  TTWO:
    name: Take-Two Interactive Software, Inc. Common Stock
    sector: ''
    market_cap: 38,566,852,252
  AMZN:
    name: Amazon.com, Inc. Common Stock
    sector: ''
    market_cap: 2,374,969,274,881
  MSTR:
    name: MicroStrategy Incorporated Common Stock Class A
    sector: ''
    market_cap: 112,040,275,948
  CTSH:
    name: Cognizant Technology Solutions Corporation Class A Common Stock
    sector: ''
    market_cap: 33,982,589,296
  CSGP:
    name: CoStar Group, Inc. Common Stock
    sector: ''
    market_cap: 40,034,959,209
  NVDA:
    name: NVIDIA Corporation Common Stock
    sector: ''
    market_cap: 4,457,880,000,000
  BKNG:
    name: Booking Holdings Inc. Common Stock
    sector: ''
    market_cap: 175,204,921,420
  'ON':
    name: ON Semiconductor Corporation Common Stock
    sector: ''
    market_cap: 19,491,700,459
  ISRG:
    name: Intuitive Surgical, Inc. Common Stock
    sector: ''
    market_cap: 168,512,635,940
  MRVL:
    name: Marvell Technology, Inc. Common Stock
    sector: ''
    market_cap: 66,682,548,000
  ADI:
    name: Analog Devices, Inc. Common Stock
    sector: ''
    market_cap: 111,134,783,494
  AEP:
    name: American Electric Power Company, Inc. Common Stock
    sector: ''
    market_cap: 60,164,410,838
  AMD:
    name: Advanced Micro Devices, Inc. Common Stock
    sector: ''
    market_cap: 280,362,475,712
  ADP:
    name: Automatic Data Processing, Inc. Common Stock
    sector: ''
    market_cap: 123,866,243,255
  AZN:
    name: AstraZeneca PLC American Depositary Shares
    sector: ''
    market_cap: 228,103,655,263
  CDNS:
    name: Cadence Design Systems, Inc. Common Stock
    sector: ''
    market_cap: 95,932,829,400
  CSX:
    name: CSX Corporation Common Stock
    sector: ''
    market_cap: 66,051,334,606
  HON:
    name: Honeywell International Inc. Common Stock
    sector: ''
    market_cap: 137,334,475,326
  MAR:
    name: Marriott International Class A Common Stock
    sector: ''
    market_cap: 70,557,321,513
  MU:
    name: Micron Technology, Inc. Common Stock
    sector: ''
    market_cap: 133,052,783,258
  XEL:
    name: Xcel Energy Inc. Common Stock
    sector: ''
    market_cap: 43,369,281,559
  EXC:
    name: Exelon Corporation Common Stock
    sector: ''
    market_cap: 45,772,624,164
  PEP:
    name: PepsiCo, Inc. Common Stock
    sector: ''
    market_cap: 198,803,700,793
  ROP:
    name: Roper Technologies, Inc. Common Stock
    sector: ''
    market_cap: 57,506,675,269
  TXN:
    name: Texas Instruments Incorporated Common Stock
    sector: ''
    market_cap: 170,208,660,780
  AXON:
    name: Axon Enterprise, Inc. Common Stock
    sector: ''
    market_cap: 66,139,990,700
  MDLZ:
    name: Mondelez International, Inc. Class A Common Stock
    sector: ''
    market_cap: 80,004,644,824
  NFLX:
    name: Netflix, Inc. Common Stock
    sector: ''
    market_cap: 514,857,757,867
  GOOGL:
    name: Alphabet Inc. Class A Common Stock
    sector: ''
    market_cap: 2,435,973,480,000
  DXCM:
    name: DexCom, Inc. Common Stock
    sector: ''
    market_cap: 30,925,364,198
  TMUS:
    name: T-Mobile US, Inc. Common Stock
    sector: ''
    market_cap: 275,705,155,929
  LULU:
    name: lululemon athletica inc. Common Stock
    sector: ''
    market_cap: 21,733,195,925
  MELI:
    name: MercadoLibre, Inc. Common Stock
    sector: ''
    market_cap: 119,326,411,538
  KDP:
    name: Keurig Dr Pepper Inc. Common Stock
    sector: ''
    market_cap: 46,757,342,303
  AVGO:
    name: Broadcom Inc. Common Stock
    sector: ''
    market_cap: 1,434,417,544,466
  VRSK:
    name: Verisk Analytics, Inc. Common Stock
    sector: ''
    market_cap: 37,030,055,914
  FTNT:
    name: Fortinet, Inc. Common Stock
    sector: ''
    market_cap: 56,939,330,162
  CHTR:
    name: Charter Communications, Inc. Class A Common Stock New
    sector: ''
    market_cap: 35,045,149,021
  TSLA:
    name: Tesla, Inc. Common Stock
    sector: ''
    market_cap: 1,063,269,226,259
  NXPI:
    name: NXP Semiconductors N.V. Common Stock
    sector: ''
    market_cap: 52,228,059,500
  FANG:
    name: Diamondback Energy, Inc. Common Stock
    sector: ''
    market_cap: 41,115,713,624
  META:
    name: Meta Platforms, Inc. Class A Common Stock
    sector: ''
    market_cap: 1,932,590,436,718
  PANW:
    name: Palo Alto Networks, Inc. Common Stock
    sector: ''
    market_cap: 111,395,608,000
  WDAY:
    name: Workday, Inc. Class A Common Stock
    sector: ''
    market_cap: 59,292,690,000
  CDW:
    name: CDW Corporation Common Stock
    sector: ''
    market_cap: 21,352,416,575
  GOOG:
    name: Alphabet Inc. Class C Capital Stock
    sector: ''
    market_cap: 2,444,076,460,000
  PYPL:
    name: PayPal Holdings, Inc. Common Stock
    sector: ''
    market_cap: 64,631,349,098
  SHOP:
    name: Shopify Inc. Class A Subordinate Voting Shares
    sector: ''
    market_cap: 194,101,152,110
  KHC:
    name: The Kraft Heinz Company Common Stock
    sector: ''
    market_cap: 32,856,714,208
  TEAM:
    name: Atlassian Corporation Class A Common Stock
    sector: ''
    market_cap: 44,116,730,966
  CCEP:
    name: Coca-Cola Europacific Partners plc Ordinary Shares
    sector: ''
    market_cap: 43,419,003,856
  TTD:
    name: The Trade Desk, Inc. Class A Common Stock
    sector: ''
    market_cap: 26,650,719,020
  BKR:
    name: Baker Hughes Company Class A Common Stock
    sector: ''
    market_cap: 42,678,707,278
  ZS:
    name: Zscaler, Inc. Common Stock
    sector: ''
    market_cap: 41,990,344,260
  PDD:
    name: PDD Holdings Inc. American Depositary Shares
    sector: ''
    market_cap: 162,208,804,748
  CRWD:
    name: CrowdStrike Holdings, Inc. Class A Common Stock
    sector: ''
    market_cap: 105,803,357,381
  DDOG:
    name: Datadog, Inc. Class A Common Stock
    sector: ''
    market_cap: 45,210,191,470
  PLTR:
    name: Palantir Technologies Inc. Class A Common Stock
    sector: ''
    market_cap: 443,533,139,030
  ABNB:
    name: Airbnb, Inc. Class A Common Stock
    sector: ''
    market_cap: 75,206,144,783
  DASH:
    name: DoorDash, Inc. Class A Common Stock
    sector: ''
    market_cap: 110,724,628,506
  APP:
    name: Applovin Corporation Class A Common Stock
    sector: ''
    market_cap: 154,235,195,786
  GFS:
    name: GlobalFoundries Inc. Ordinary Shares
    sector: ''
    market_cap: 17,853,555,055
  CEG:
    name: 'Constellation Energy Corporation Common Stock '
    sector: ''
    market_cap: 105,234,583,238
  WBD:
    name: 'Warner Bros. Discovery, Inc. Series A Common Stock '
    sector: ''
    market_cap: 26,992,158,283
  GEHC:
    name: 'GE HealthCare Technologies Inc. Common Stock '
    sector: ''
    market_cap: 32,872,466,664
  LIN:
    name: Linde plc Ordinary Shares
    sector: ''
    market_cap: 221,522,241,107
  ARM:
    name: Arm Holdings plc American Depositary Shares
    sector: ''
    market_cap: 146,708,063,862
data_sources:
  yfinance:
    enabled: true
    periods:
    - daily_3mo
    - weekly_5y
    - monthly_max
  sec_edgar:
    enabled: false
expected_files:
  yfinance: 300
  sec_edgar: 0
validation:
  timeout_seconds: 1800
  required_success_rate: 0.95
ticker_count: 100
last_updated: '2025-08-10T03:29:29.679994'
