# data/config/litellm_config.yaml
model_list:
  # 映射 Claude Code 可能请求的所有模型名称
  - model_name: claude-3-5-sonnet-20241022
    litellm_params:
      model: ollama_chat/gpt-oss:20b
      api_base: http://localhost:11434
  - model_name: claude-3-5-haiku-20241022
    litellm_params:
      model: ollama_chat/gpt-oss:20b
      api_base: http://localhost:11434
  - model_name: claude-sonnet-4-20250514
    litellm_params:
      model: ollama_chat/gpt-oss:20b
      api_base: http://localhost:11434
  - model_name: claude-3-haiku
    litellm_params:
      model: ollama_chat/gpt-oss:20b
      api_base: http://localhost:11434

# 通用设置
general_settings:
  max_budget: 100
  budget_duration: 30d

