# SEC Edgar Magnificent 7 Configuration  
# Data source: SEC EDGAR database
source: sec-edgar

# Email for SEC EDGAR API requests (required)
email: "ZitianSG (wangzitian0@gmail.com)"

# Magnificent 7 companies by CIK numbers
tickers:
  - "0000320193"  # Apple Inc. (AAPL)
  - "0000789019"  # Microsoft Corporation (MSFT)
  - "0001018724"  # Amazon.com Inc. (AMZN)
  - "0001652044"  # Alphabet Inc. (GOOGL)
  - "0001318605"  # Tesla Inc. (TSLA)
  - "0001065280"  # Netflix Inc. (NFLX)
  - "0001326801"  # Meta Platforms Inc. (META)

# Number of recent filings to fetch per company per filing type
count: 8

# SEC filing types to collect
file_types:
  - "10K"    # Annual reports
  - "10Q"    # Quarterly reports
  - "8K"     # Current reports
  - "13F"    # Institutional investment reports
