job: yfinance_nasdaq100
source: yfinance
description: "Fetch data for NASDAQ-100 stocks (using yfinance library)"
tickers:
  - ADBE
  - AMD
  - ABNB
  - GOOGL
  - GOOG
  - AMZN
  - AEP
  - AMGN
  - ADI
  - ANSS
  - AAPL
  - AMAT
  - APP
  - ARM
  - ASML
  - AZN
  - ADSK
  - ADP
  - AXON
  - BKR
  - BIIB
  - BKNG
  - AVGO
  - CDNS
  - CDW
  - CHTR
  - CTSH
  - CMCSA
  - CCEP
  - CEG
  - CPRT
  - CSGP
  - COST
  - CRWD
  - CSX
  - DDOG
  - DXCM
  - FANG
  - DASH
  - DOCU
  - EA
  - EXC
  - FAST
  - FTNT
  - FVRR
  - FSLY
  - GEHC
  - GILD
  - GFS
  - HON
  - IDXX
  - INTC
  - INTU
  - ISRG
  - KDP
  - KLAC
  - LRCX
  - LIN
  - LULU
  - LYFT
  - MAR
  - MTCH
  - MRVL
  - MELI
  - META
  - MCHP
  - MU
  - MSFT
  - MSTR
  - MDLZ
  - MDB
  - MNST
  - NFLX
  - NVDA
  - NXPI
  - ORLY
  - ODFL
  - "ON"
  - OKTA
  - PCAR
  - PLTR
  - PANW
  - PAYX
  - PYPL
  - PDD
  - SNAP
  - SIRI
  - TTD
  - TEAM
  - UBER
  - WBD
  - WBA
  - WDAY
  - XEL
  - RBLX
  - ROP
  - VEEV
  - VRSN
  - VRTX
  - ZS
data_periods:
  - oid: "nasdaq100D1"    # Represents 1 year of daily data
    period: "1y"
    interval: "1d"
  - oid: "nasdaq100W7"    # Represents 7 years of weekly data
    period: "7y"
    interval: "1wk"
  - oid: "nasdaq100M30"   # Represents 30 years of monthly data
    period: "30y"
    interval: "1mo"
