data_periods:
- interval: 1d
  oid: us_all_D1
  period: 1y
- interval: 1wk
  oid: us_all_W7
  period: 7y
- interval: 1mo
  oid: us_all_M30
  period: 30y
description: Yahoo Finance data for all US stocks (placeholder)
job: yfinance_us_all
note: 'To be implemented: fetch from stock screener APIs'
source: yfinance
