---
# p3_ready_setup.yml
# P3 Ready Command Integration Playbook
# Complete environment orchestration for robust development setup

- name: P3 Ready - Complete Development Environment Setup
  hosts: localhost
  become: no
  gather_facts: yes
  vars:
    repo_dir: "{{ lookup('env','PWD') }}"
    run_git_pull: false  # P3 ready should not modify git state
    
  tasks:
    - name: Display P3 Ready environment setup banner
      debug:
        msg: |
          🎭 P3 Ready - Ansible Environment Orchestration
          ============================================
          Repository: {{ repo_dir }}
          Host: {{ ansible_hostname }}
          Date: {{ ansible_date_time.iso8601 }}

    - name: Check system requirements
      include_tasks: roles/system_requirements_check.yml

    - name: Setup Podman machine and containers
      include_tasks: roles/podman_neo4j_setup.yml

    - name: Verify Python environment
      include_tasks: roles/python_environment_check.yml

    - name: Setup data directories
      include_tasks: roles/data_directory_setup.yml

    - name: Final environment validation
      include_tasks: roles/final_validation.yml

    - name: P3 Ready setup complete
      debug:
        msg: |
          🎉 P3 Ready Setup Complete!
          =========================
          ✅ Podman machine running and accessible
          ✅ Neo4j container deployed and healthy
          ✅ Python environment validated
          ✅ Data directories initialized
          ✅ All services responding correctly
          
          🚀 Environment ready for development:
          • p3 build f2        # Quick test build
          • p3 test f2         # Fast validation
          • p3 ship 'title' #  # Create PR