---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-logs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-config
  namespace: default
data:
  NEO4J_AUTH: "neo4j/finance123"
  NEO4J_PLUGINS: '["apoc"]'
  NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
  NEO4J_dbms_memory_heap_initial__size: "512m"
  NEO4J_dbms_memory_heap_max__size: "1G"
  NEO4J_dbms_default__listen__address: "0.0.0.0"
  NEO4J_dbms_connector_bolt_listen__address: "0.0.0.0:7687"
  NEO4J_dbms_connector_http_listen__address: "0.0.0.0:7474"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  namespace: default
  labels:
    app: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j:5.18-community
        ports:
        - containerPort: 7474
          name: http
        - containerPort: 7687
          name: bolt
        envFrom:
        - configMapRef:
            name: neo4j-config
        volumeMounts:
        - name: neo4j-data
          mountPath: /data
        - name: neo4j-logs
          mountPath: /logs
        resources:
          limits:
            memory: "1.5Gi"
            cpu: "800m"
          requests:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 7687
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 7687
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: neo4j-data
        persistentVolumeClaim:
          claimName: neo4j-data-pvc
      - name: neo4j-logs
        persistentVolumeClaim:
          claimName: neo4j-logs-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
  namespace: default
  labels:
    app: neo4j
spec:
  type: NodePort
  ports:
  - port: 7474
    targetPort: 7474
    nodePort: 30474
    name: http
  - port: 7687
    targetPort: 7687
    nodePort: 30687
    name: bolt
  selector:
    app: neo4j