# Production Scenario Configuration
description: "Production environment with full data processing"

# Available data sources for production
data_sources:
  - "yfinance"
  - "sec_edgar"
  - "federal_reserve"  # Additional production sources
  - "bloomberg"

processing_mode: "full"  # Complete processing

# Strict quality thresholds for production
quality_thresholds:
  min_success_rate: 0.95
  max_error_rate: 0.05
  timeout_minutes: 60

# Output settings
output_formats:
  - "json"
  - "parquet"  # More efficient for large datasets
  - "sql"
  
output_settings:
  save_intermediate: false  # Save space
  debug_mode: false
  verbose_logging: false
  compress_output: true

# Production resource limits
resource_limits:
  max_concurrent_requests: 50
  memory_limit_mb: 8192
  disk_space_mb: 100000

# Production optimizations
optimizations:
  cache_enabled: true
  skip_validation: false
  parallel_processing: true
  batch_processing: true
  
# Production monitoring
monitoring:
  health_checks: true
  metrics_collection: true
  alert_on_failures: true
  performance_tracking: true