---
# init.yml - Main Ansible Playbook
# This playbook sets up the complete local development environment.
# It delegates application dependencies to Pixi and handles system-level
# setup, which exclusively uses Docker for Neo4j.

- name: Initial Environment Setup
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    # The project directory, discovered from the environment.
    repo_dir: "{{ lookup('env','PWD') }}"
    # Command for initializing data submodules.
    data_repo_command: "git submodule update --init --recursive"
    # Docker container configuration
    neo4j_container_name: "my-finance-neo4j"
    neo4j_image_name: "neo4j:5.18-community"

  tasks:
    - name: Check if current directory is a Git repository
      stat:
        path: "{{ repo_dir }}/.git"
      register: git_repo
      become: false

    - name: Fail if current directory is not a Git repository
      fail:
        msg: "The setup must be run from the root of the Git repository. Current directory: {{ repo_dir }}"
      when: not git_repo.stat.exists
      become: false

    - name: Setup Pixi application environment
      include_tasks: roles/pixi_setup.yml

    - name: Setup and start Neo4j Docker container
      include_tasks: roles/docker_setup.yml

    - name: Initialize or update data repositories
      include_tasks: roles/repo_data.yml

    - name: Final summary
      debug:
        msg: |
          🎉 Ansible setup complete!
          
          Your environment is configured. Here's a summary:
          
          - ✅ Pixi environment is ready.
          - ✅ Data submodules are initialized.
          - ✅ Neo4j is running in a Docker container named '{{ neo4j_container_name }}'.
          
          Next Steps:
          1. Activate the environment: `pixi shell`
          2. Run key tasks:
             - `pixi run status` (check data status)
             - `pixi run neo4j-status` (check the database via Docker)
             - `pixi run build-m7` (build a small test dataset)
