name: Claude Code GitHub Actions

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: write

jobs:
  claude_action:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Pixi Environment
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.50.2

      - name: Create Project Structure
        run: |
          # Ensure required directories exist for the project
          mkdir -p common/config data/reports data/llm/configs
          
          # Create minimal test configuration
          echo "test_mode: true" > common/config/test_config.yml
          echo "dataset_name: fast_2" > common/config/list_fast_2.yml
          echo "cli_alias: f2" >> common/config/list_fast_2.yml

      - name: Run Claude Code Action
        uses: anthropics/claude-code-action@v1
        with:
          api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}